# Maintain a consistent coding style throughout the entire project codebase to
# ensure readability and maintainability.  Consistent style not only improves
# collaboration but also makes the code easier to review and debug.
#
# This is a configuration file for Prettier, a code formatter that supports
# many languages and can be integrated into most editors.  It is a tool that
# can be used to automatically format code to a consistent style and enforce
# code style rules.  It can be used to format code on save, format code on
# commit, and format code on demand.  It can also be used to format code in a
# CI/CD pipeline to ensure that all code is formatted consistently.  For more
# information about, refer to the official documentation at:
#
#       https://prettier.io/
#
# The rules are still a work in progress and subject to change.  I still need
# to think about this configuration, and for now this is a base template.

---
endOfLine: lf
printWidth: 120
semi: true
singleQuote: false
tabWidth: 4
trailingComma: es5
useTabs: false

overrides:
  - files: "*.md"
    excludeFiles: "CHANGELOG.md"
    options:
      parser: markdown
      printWidth: 80
      proseWrap: always
      tabWidth: 2
  - files: "*.css"
    options:
      parser: css
      printWidth: 80
  - files: "*.scss"
    options:
      parser: scss
      printWidth: 80
  - files: "*.json"
    options:
      parser: json
      printWidth: 80
      tabWidth: 2
  - files: "*.jsonc"
    options:
      parser: jsonc
      printWidth: 80
      tabWidth: 2
  - files: "*.yaml"
    options:
      parser: yaml
      printWidth: 80
      tabWidth: 2
